apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: purestanley-webapp-hpa
  namespace: purestanley-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: purestanley-webapp
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50